openapi: 3.0.0
info:
  title: API
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: API de desenvolvimento MegaHack
paths:
  /clientes:
    get:
      summary: Lista de clientes
      description: Consulta a lista de clientes cadastrados.
      responses:
        "201":
          description: JSON array de clientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cliente"
    post:
      summary: Cadastra cliente
      description: Cadastra um novo cliente.
      requestBody:
        content:
          application/json:
            schema:
              required: true
              $ref: "#/components/schemas/Cliente"
      responses:
        "201":
          description: Novo cliente cadastrado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cliente"
        "500":
          description: Falha no cadastro.
  /clientes/{cpf}:
    get:
      summary: Consulta cliente por CPF
      description: Consulta um cliente por CPF.
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: JSON de cliente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cliente"
  /clientes/{cpf}/historico:
    get:
      summary: Consulta historico por CPF
      description: Consulta o historico de faturas por CPF.
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: JSON de historico
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Historico"
  /clientes/{cpf}/extrato:
    get:
      summary: Consulta extrato por CPF
      description: Consulta o extrato de faturas por CPF.
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: JSON de extrato
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Extrato"
  /clientes/{cpf}/assinar-pre-pago:
    put:
      summary: Assinar contrato pré-pago
      description: Operação para contratação da modalidade pré-paga.
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssinaturaRequest"
      responses:
        "204":
          description: Assinatura realizada com sucesso.
        "400":
          description: Cliente não encontrado.
  /clientes/{cpf}/assinar-pos-pago:
    put:
      summary: Assinar contrato pós-pago
      description: Operação para contratação da modalidade pós-paga.
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: Assinatura realizada com sucesso.
        "400":
          description: Cliente não encontrado.
  /aparelhos:
    get:
      summary: Lista de aparelhos
      description: Consulta a lista de aparelhos cadastrados.
      responses:
        "200":
          description: JSON array de aparelhos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Aparelho"
components:
  schemas:
    Cliente:
      title: Cliente
      type: object
      properties:
        cpf:
          type: integer
          format: int64
        nome:
          type: string
        email:
          type: string
        cep:
          type: integer
          format: int64
        cidade:
          type: string
        uf:
          type: string
        saldo_valor:
          type: number
        saldo_cota:
          type: number
        cota_contratada:
          type: boolean
        cota_media_kw:
          type: number
        cota_media_vl:
          type: number
      description: Dados do Cliente
    Historico:
      title: Historico
      type: object
      properties:
        cpf_cliente:
          type: integer
          format: int64
        competencia:
          type: integer
          format: int64
        valor:
          type: number
        pago:
          type: boolean
      description: Historico do Cliente
    Extrato:
      title: Extrato
      type: object
      properties:
        cpf_cliente:
          type: integer
          format: int64
        descricao:
          type: string
        valor:
          type: number
          format: double
        operacao:
          type: string
          enum:
            - ADD
            - SUB
        data:
          type: string
          format: date-time
        criado_em:
          type: string
          format: date-time
      description: Extrato do Cliente
    Aparelho:
      title: Aparelho
      type: object
      properties:
        nome:
          type: string
        consumo:
          type: number
          format: double
      description: Aparelho elétrico
    AssinaturaRequest:
      title: AssinaturaRequest
      type: object
      properties:
        cota:
          type: number
          format: double
        valor:
          type: number
          format: double
